### ISSUE TITLE
Cannot read environment variables

### ISSUE THREAD

**Issue by conanzxn** [revel/config#10]
**To reproduce:**

1. Set an environment variable `export ABC=test`
2. Insert the following to the app.conf `my.abc = ${ABC}`
3. Read the config and print out the value `fmt.Println(revel.Config.StringDefault("my.abc", ""))`

**Expected output:**
test

**Actual output:**

**Go version:** go version go1.11 darwin/amd64
**Revel version**:

```
Revel Version = "0.20.0"
Revel BuildDate = "2018-09-23"
Revel MinimumGoVersion = ">= go1.8"

Revel Command Utility Tool
Version 0.20.1
Build Date 2018-09-30
Minimum Go Version >= go1.8
Compiled By   go1.11 darwin/amd64

go version go1.11 darwin/amd64
```

**Comment by notzippy** [comment]
Thankyou for the submission, this was because of the revel/cmd package and has already been resolved there. Please update your local revel tool with a `go get -u github.com/revel/cmd/revel`
