### ISSUE TITLE
Tags v14 to v18 point to the same commit.

### ISSUE THREAD

**Issue by KonstantinCodes** [revel/config#6]
In this way, I can't lock down v17 in my Gopkg.toml file.

**Comment by Steve-hyas** [comment]
revel config has not changed in these revisions

**Comment by notzippy** [comment]
We haven't made any changes to this project in the past four releases.

**Comment by KonstantinCodes** [comment]
Sorry, my bad!

**Comment by notzippy** [comment]
For that I used the overrides

```
[[override]]
  branch = "master"
  name = "github.com/revel/log15"

[[override]]
  branch = "develop"
  name = "github.com/revel/cron"

[[override]]
  branch = "master"
  name = "github.com/xeonx/timeago"
```

BTW if you want to compile a specific version of revel command line you can use this process
https://github.com/revel/meta/pull/11
