### ISSUE TITLE
You cannot have multi-lines without defining a section

### ISSUE THREAD

**Issue by Zauberstuhl** [revel/config#7]
If you have not section in your config file defined (you assume everything should be in DEFAULT)
then multi-line support will not work.

The fix is to include the default section.

```
[DEFAULT]

multi.line=test
 ...
 this is multi
 line

```

Maybe this not a real issue more like a documentation thing. I stumbled over this when i started using https://revel.github.io/manual/i18n-messages.html

**Comment by notzippy** [comment]
Very true, looking at this  [line](https://github.com/revel/config/blob/master/read.go#L80) it shows that the section must not be empty to do a multiline. I will update the skeleton to add the default section and make a note on the docs
